name: PyTest

on:
  push:
    branches: [ master, pyglet-1.5-maintenance]
  pull_request:
    branches: [ master, pyglet-1.5-maintenance]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        sudo apt-get install xvfb
    - name: Run tests
      run: |
        xvfb-run pytest -v tests/unit

        xvfb-run pytest -v tests/integration/app
        xvfb-run pytest -v tests/integration/font
        # xvfb-run pytest -v tests/integration/graphics
        xvfb-run pytest -v tests/integration/image
        xvfb-run pytest -v tests/integration/model
        xvfb-run pytest -v tests/integration/platform
        xvfb-run pytest -v tests/integration/resource
        xvfb-run pytest -v tests/integration/text
        xvfb-run pytest -v tests/integration/window
