name: PyTest

on:
  push:
    branches: [ master, pyglet-1.5-maintenance]
  pull_request:
    branches: [ master, pyglet-1.5-maintenance]

jobs:
  test1:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          sudo apt-get install xvfb
      - name: Run tests
        run: |
          xvfb-run pytest tests/unit

  test2:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    name: Python ${{ matrix.python-version }} OSX
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          sudo apt-get install xvfb
      - name: Run tests
        run: |
          xvfb-run pytest tests/unit
